# Generated by Django 5.2.12 on 2026-04-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministore', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='productimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
