# Generated by Django 5.2.13 on 2026-04-29 15:57

import ministore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministore', '0003_alter_productimage_options_productimage_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=ministore.models.category_image_path),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
