# Generated by Django 5.2.13 on 2026-05-14 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ministore', '0004_category_image_category_slug'),
        ('ministore', '0006_product_is_available'),
    ]

    operations = [
    ]
