# Generated by Django 5.2.13 on 2026-05-14 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ministore', '0007_merge_20260514_1838'),
        ('ministore', '0007_merge_20260514_2210'),
    ]

    operations = [
    ]
