# Generated by Django 5.2.12 on 2026-05-15 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministore', '0009_orderstatushistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_changed', models.CharField(choices=[('price', 'Price'), ('stock', 'Stock')], max_length=20)),
                ('old_value', models.CharField(max_length=255)),
                ('new_value', models.CharField(max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='manual', help_text='manual, bulk, or flash_sale', max_length=50)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='ministore.product')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
